@url = http://localhost:8080
POST {{url}}/api/add-msg/
content-type: application/json
secret: tddDDdfklsjj8884820ljsdhzzzqqq392992992idkjdksfl832uhds94skdh4uhs92SSSSt

{
    "command": "some",
    "msgId": 3,
    "queueName": "test1",
    "userName": "someUser"
}