POST https://t.a3b.me/mcore
content-type: application/json
secret: !ouC!6s5YuViP!RQylqkq5FzeYs*W2!

{
    "command": "some",
    "msgId": 3,
    "queueName": "test1",
    "userName": "someUser",
    
}