@url = http://localhost:8080
POST {{url}}/api/get-msg/
content-type: application/json
secret: tddDDdfklsjj8884820ljsdhzzzqqq392992992idkjdksfl832uhds94skdh4uhs92SSSSt

{
    "queueName": "test1"
}