version: "3.1"

networks:
  dnet:
    name: dnetmy
    driver: bridge

services:
  redis:
      image: "redis:alpine"
      container_name: redis
      command: redis-server --save 120 1 --loglevel warning
      ports:
        - "6379:6379"
      restart: unless-stopped
      networks:      
        - dnet   
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - TRANSMISSION_WEB_HOME= #optional
      # - USER= #optional
      # - PASS= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - ./config/:/config
      - ./downloads/:/downloads
      - ./watch/:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  tbot:
    image: ghcr.io/ishua/a3bot5-tbot:latest
    # image: tbot
    # build:
    #   context: ./
    #   dockerfile: ./tbot/Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - dnet
    volumes:
      - ./tbot/conf/:/conf
  restjobs:
    image: ghcr.io/ishua/a3bot5-restjobs:latest
    # image: restjobs
    # build:
    #   context: ./
    #   dockerfile: ./restjobs/Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - dnet
    volumes:
      - ./restjobs/conf/:/conf
  ytd2feed:
    image: ghcr.io/ishua/a3bot5-ytd2feed:latest
    # image: ytd2feed
    # build:
    #   context: ./
    #   dockerfile: ./ytd2feed/Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - dnet
    volumes:
      - ./ytd2feed/conf/:/srv/conf
      - ./ytd2feed/data/:/srv/data
  transmission_bot:
    image: ghcr.io/ishua/a3bot5-transmission:latest
    # image: transmission_bot
    # build:
    #   context: ./
    #   dockerfile: ./transmission/Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
      - transmission
    networks:
      - dnet
    volumes:
      - ./transmission/conf/:/srv/conf
  fsnotes:
    image: ghcr.io/ishua/a3bot5-fsnotes:latest
    # image: fsnotes
    # build:
    #   context: /Users/amamyrin/Documents/repo/a3bot5/
    #   dockerfile: ./fsnotes/Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
      - tbot
    networks:
      - dnet
    volumes:
      - ./fsnotes/conf/:/conf
      - ./fsnotes/temp/data/:/data