version: "3.1"

networks:
  dnet:
    name: dnetmy
    driver: bridge

services:
  tbot:
    image: ghcr.io/ishua/a3bot5:latest
    # image: tbot
    # build:
    #   context: ./
    #   dockerfile: ./tbot/Dockerfile
    networks:
      - dnet
    volumes:
      - ./tbot/conf/:/conf