version: 0.0.1
# redis: localhost
path2content: data
url2content: https://localhost/
users: 
  - name: Username
    feedName: rss
    feedDescription: my rss generate
    format: ba[ext=m4a]/ba[ext=mp3]/ba[ext=aac]