version: 0.0.1
#redis: localhost:6379
tbotchannel: tbot
path2content: temp
url2content: https://localhost/
users: 
  - user: AlekseyIm
    feed_name: rss
    feed_description: my rss generate
    format: ba[ext=m4a]/ba[ext=mp3]/ba[ext=aac]